#!/bin/sh

# This script runs after Xcode Cloud clones the repo
# It creates Secrets.swift from the environment variable

echo "Creating Secrets.swift from environment variable..."

cat > "$CI_PRIMARY_REPOSITORY_PATH/Sling/Secrets.swift" << EOF
import Foundation

// Auto-generated by Xcode Cloud CI
// DO NOT COMMIT THIS FILE

struct Secrets {
    static let anthropicAPIKey = "${ANTHROPIC_API_KEY}"
    static let linearAPIKey = "${LINEAR_API_KEY}"
}
EOF

echo "Secrets.swift created successfully"
